export const ACCOUNT_LOGIN = 'ACCOUNT_LOGIN';
export const ACCOUNT_LOGIN_SUCCESS = 'ACCOUNT_LOGIN_SUCCESS';
export const ACCOUNT_LOGOUT = 'ACCOUNT_LOGOUT';

export const CREATE_ACCOUNT = 'CREATE_ACCOUNT';
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';

export const CREATE_REMIND = 'CREATE_REMIND';
export const CREATE_REMIND_SUCCESS = 'CREATE_REMIND_SUCCESS';

export const DELETE_REMIND = 'DELETE_REMIND';
export const DELETE_REMIND_SUCCESS = 'DELETE_SUCCESS';

export const RESET_COMPLETE = 'RESET_COMPLETE';

export const RESET_ERROR = 'RESET_ERROR';
export const SET_ERROR = 'SET_ERROR';

export const VERIFY = 'VERIFY';
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS';

export const ADD_PHONE = 'ADD_PHONE';
export const ADD_PHONE_SUCCESS = 'ADD_PHONE_SUCCESS';